### PR TITLE
Propose to use express-interceptor instead of express-hijackresponse

### PR DESCRIPTION
**Pull request by fer8a**
Hello again @gustavnikolaj,

Changes in the code removing hijackresponse and adding interceptor.

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
LGTM! Thanks a lot :-)

**Comment by p1nox** [comment]
Hey guys, was it the new version pushed into npm registry?

**Comment by gustavnikolaj** [comment]
Oh, I'll make sure to check next time I'm at a computer.

Den mandag den 25. maj 2015 skrev Raul Pino <notifications@github.com>:

**Comment by gustavnikolaj** [comment]
Version 3.1.0 is published now.

**Comment by p1nox** [comment]
Awesome! :feelsgood: cc @fer8a @flockonus

**Pull request merged**
